name: Release package

on:
  push:
    branches:
      - testing/gz-release
    paths:
      - ".github/workflows/release.yml"
  release:
    types:
      - published

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  contents: write
  issues: write

jobs:
  create-release:
    if: github.repository == 'LikeLakers2/browser-compat-data' && github.event_name == 'push'
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (BCD)
        uses: actions/checkout@v5

      - name: Create release
        run: |
          VERSION=v$(jq -r '.version' package.json)
          gh release create $VERSION --title=$VERSION --target $GITHUB_SHA --latest

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org/"

      - run: npm run build

      - run: gzip -k build/data.json

      - name: Add JSON as a release asset
        run: |
          gh release upload ${GITHUB_REF#refs/*/} build/data.json
          
